# Generated by Django 3.1.4 on 2021-01-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=40)),
                ('ptime', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('pdate', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('rtime', models.IntegerField()),
                ('rdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subprojects',
            fields=[
                ('spid', models.IntegerField(primary_key=True, serialize=False)),
                ('spname', models.CharField(max_length=40)),
                ('sptime', models.DecimalField(decimal_places=1, max_digits=12)),
                ('spdate', models.DateField(blank=True, null=True)),
                ('numrecord', models.IntegerField()),
            ],
            options={
                'db_table': 'subprojects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
